Token list service refac
Kolektivo/kolektivo-dapp pull request #125
Opened 2022-08-24 21:20 UTC by brandonseydel

2022-08-25 11:19 UTC, dkent600 requested changes
I know you didn't request my review on this.  But just in case, I just wanted to hold it up.  If you really want to submit it, i'll feedback.

2022-08-25 16:36 UTC, brandonseydel commented
> I know you didn't request my review on this. But just in case, I just wanted to hold it up. If you really want to submit it, i'll feedback.

Yes please review.

2022-08-25 17:28 UTC, dkent600 requested changes

2022-08-25 17:28 UTC, dkent600 commented on src/services/services.ts
> +      this.contractsDeploymentService.initialize(targetNetwork),
ethereumService and contractsDeploymentService must be initialized before contractsService

2022-08-25 17:28 UTC, dkent600 commented on src/services/token-list-service.ts
> +      return;
should end the timer before returning.

In general I am in favor of returning from functions only from a single location.

2022-08-26 03:10 UTC, dkent600 requested changes

2022-08-26 03:10 UTC, dkent600 commented on src/app.ts
> +      .catch(() => void this.notificationService.toast({ type: 'danger', message: 'There was an error initializing the application' }));
Should also log the details (error message and stack trace)

2022-08-26 21:25 UTC, dkent600 approved these changes

2022-08-27 01:26 UTC, merged